exports.roleNameFile={
    "CTHSSV":"Phòng Công tác học sinh sinh viên",
    "PDH":"Phòng Đại học",
    "PSDH":"Phòng Sau đại học",
    "DTMT":"Phòng điện toán và máy tính",
    "KTCL":"Phòng khảo thí và kiểm định chất lượng",
    "TC":"Phòng tài chính",
    "CLC":"TDT Creative Language Center",
    "TH":"Trung tâm tin học",
    "SDTC":"Trung tâm đào tạo phát triển xã hội (SDTC)",
    "ATEM":"Trung tâm phát triển Khoa học quản lý và Ứng dụng công nghệ (ATEM)",
    "KL":"Trung tâm hợp tác doanh nghiệp và cựu sinh viênKhoa Luật",
    "ET":"Trung tâm ngoại ngữ - tin học – bồi dưỡng văn hóa",
    "UEF":"Viện chính sách kinh tế và kinh doanh",
    "MTCN":"Khoa Mỹ thuật công nghiệp",
    "DDT":"Khoa Điện – Điện tử",
    "IT":"Khoa Công nghệ thông tin",
    "QTKD":"Khoa Quản trị kinh doanh",
    "BHLD":"Khoa Môi trường và bảo hộ lao động",
    "LDCD":"Khoa Lao động công đoàn",
    "TCNH":"Khoa Tài chính ngân hàng",
    "GDQT":"Khoa giáo dục quốc tế",
    "SV":"Sinh Viên",
    "ADMIN":"Quản trị viên"
}